### ISSUE TITLE
Feature Request: MIUI lock screen support

### ISSUE THREAD

**Issue by cary-hu** [Yubyf/QuoteLock#10]
QuoteLockX is a great plugin to display some extra info in lockscreen, but just support Only near-AOSP Android ROMs, it'a pity.

so, could this plugin support any other ROM, like MIUI?

**Comment by Yubyf** [comment]
Thanks for your feedback.
Indeed, some people have asked me to adapt for MIUI before, and I hope to do this too. However, since there is no MIUI device around me and I have less free time too, the adaptation task can only be scheduled after I get a MIUI device.

**Comment by moedwyn** [comment]
It is an awesome plugin 👍👍👍
it works in A12L too.
Thanks dev!!!

*for A12 users, don't forget to disable the double line clock option in lockscreen setting, so the quote will not be covered

**Comment by Yubyf** [comment]
Thank you for testing. I am delighted to see that this feature is compatible with MIUI.
