### ISSUE TITLE
請問是否可支持Hitokoto語句類型的多重選擇？

### ISSUE THREAD

**Issue by alexchiu100014** [Yubyf/QuoteLock#12]
Hitokoto的api可以使用 ?c=a&c=c
來選擇多重句子類型
希望能支援多重類型選擇

還有不知道為什麼
手機的語句永遠都是簡體（另一個軟體都是繁體）

**Comment by Yubyf** [comment]
@alexchiu100014 
感谢反馈
1. 多分类选择可以列入 TODO 排期
2. 本软件直接使用 [Hitokoto](https://developer.hitokoto.cn/) 接口返回字符串展示，而根据接口调用测试，返回字符类型基本都为简体字，而 [Hitokoto](https://developer.hitokoto.cn/) 并未提供简繁转换接口，所以您所看到的繁体信息可能为其他软件自身对字符进行转换（仅猜测）

**Comment by Yubyf** [comment]
将会在下版本更新该功能
