### ISSUE TITLE
当设备不支持通话的时候，无法正常打开xposed

### ISSUE THREAD

**Issue by linyuan9935** [Yubyf/QuoteLock#22]
如题
![Screenshot_2024-05-21-21-36-22-568_com.android.contacts-edit.jpg](https://github.com/Yubyf/QuoteLockX/assets/99480148/b72fa433-6cb2-4352-b4a9-637095ca6b7f)

**Comment by Yubyf** [comment]
您好，lsposed 未提供官方的打开操作，拨号键盘也是权宜之计，如果无拨号键盘的话还请您自行打开 lsposed 界面进行配置
