### ISSUE TITLE
Failed to download quote for BrainyQuote

### ISSUE THREAD

**Issue by harmtemolder** [Yubyf/QuoteLock#5]
Natune.net and Freakuotes work, but all 5 types of BrainyQuote say "Failed to download quote" 

---

- Device: Xiaomi Mi 9 SE
- Android version: 11 (API 30)
- LSPosed version: 1.7.2 (6379)
- QuoteLock version: 1.5.2 (14)

When I clear LSPosed logs, then update BrainyQuote in QuoteLock and check back, nothing is logged

**Comment by Yubyf** [comment]
Fixed in ad6b1fdb742faa3bca70eff003bbb9af256a1cc8

**Comment by darkbeast13** [comment]
Can you please release a build for this
I don't have clue how to build from a GitHub source

**Comment by Yubyf** [comment]
> Can you please release a build for this I don't have clue how to build from a GitHub source

~~I'll release an update in a day or two.~~

The 2.0.1 has been [released](https://github.com/Yubyf/QuoteLockX/releases/tag/v2.0.1).
