### ISSUE TITLE
Unable to create directory when trying local backup

### ISSUE THREAD

**Issue by harmtemolder** [Yubyf/QuoteLock#6]
When I go to Collections > Local > Backup I get "Unable to create directory. Retry". What am I doing wrong? 

---

- Device: Xiaomi Mi 9 SE
- Android version: 11 (API 30)
- LSPosed version: 1.7.2 (6379)
- QuoteLock version: 1.5.2 (14)

When I clear LSPosed logs, then try to backup and check back, nothing is logged

**Comment by Yubyf** [comment]
This issue is caused by [scoped storage](https://developer.android.com/about/versions/11/privacy/storage) on Android 11+ and I will fix it in the next version.
