### ISSUE TITLE
Feature Request: Integrate quotes from fortune-mod

### ISSUE THREAD

**Issue by harmtemolder** [Yubyf/QuoteLock#7]
It would be great if QuoteLock could display quotes from a local copy of [fortune-mod](https://github.com/shlomif/fortune-mod). I especially like the `science` subset

**Comment by Yubyf** [comment]
It seems difficult to add support for `fortune` because of its too many long or multi-line sentences. `QuoteLockX` can only display one line of sentences due to limited space on the lock screen.

**Comment by harmtemolder** [comment]
Yes, some of them can be long. In the terminal I use `fortune -s` to only return short quotes (`-n` would set what is considered short, default = 160 characters)

**Comment by Yubyf** [comment]
> Yes, some of them can be long. In the terminal I use `fortune -s` to only return short quotes (`-n` would set what is considered short, default = 160 characters)

Fortune_mod has been supported and I limited the max length of sentences to 160.

**Comment by harmtemolder** [comment]
Oh wow, that's great. Thank you!
