### ISSUE TITLE
请问能否支持设置 格言与来源 之间的行距

### ISSUE THREAD

**Issue by ChellyL** [Yubyf/QuoteLock#9]
如题

目前模块可以设置整个显示内容与上下内容之间的距离
能否支持自定义 格言与来源 之间的行距？中文显示时感觉格言和来源的行距太近了，不够美观，
希望能增加行距设置功能，非常感谢

**Comment by Yubyf** [comment]
谢谢反馈，下个版本可以可以添加功能

**Comment by Yubyf** [comment]
已添加
